// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onOdorSelectChange();
void onStartChange();

int odor_select;
bool start;

void initProperties(){

  ArduinoCloud.addProperty(odor_select, READWRITE, ON_CHANGE, onOdorSelectChange);
  ArduinoCloud.addProperty(start, READWRITE, ON_CHANGE, onStartChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);


#include <QueueArray.h>